eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    
logging:
  file:
    path: ./logs
    name: ${logging.file.path}/servidor-oauth.log
  logback:
    rollingpolicy:      
      max-file-size: 100MB
      max-history: 180
      total-size-cap: 2GB

server:
  port: ${PORT:0}

spring:
    application:
        name: servidor-oauth
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.115:5432/krugerdb
        username: demo
        password: demo
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect        properties:
          hibernate:
            show_sql: false