logging:  file:    path: ./logs    name: ${logging.file.path}/servicio-ciudadano.log  logback:    rollingpolicy:            max-file-size: 100MB      max-history: 180      total-size-cap: 2GB        

server:
  port: 8081

spring:
    application:
        name: servicio-ciudadano 
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.115:5432/krugerdb
        username: demo
        password: demo
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
    api-docs:
        path: /api-docs