eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    
logging:
  file:
    path: ./logs
    name: ${logging.file.path}/servidor-zuul.log
  logback:
    rollingpolicy:      
      max-file-size: 100MB
      max-history: 180
      total-size-cap: 2GB

server:
  port: 8443

spring:
    application:
        name: servidor-zuul
            
zuul:
  routes:
    paultamayo-oauth:
      service-id: servidor-oauth
      path: /api/seguridad/**
      sensitive-headers:
      - Cookie,Set-Cookie
    paultamayo-ciudadano:
      service-id: servicio-ciudadano 
      path: /api/ciudadano/**
    paultamayo-administrador:
      service-id: servicio-administrador
      path: /api/administracion/**